export { default as Hero } from './Hero/Hero'
export { default as Jobs } from './Jobs/Jobs'
export { default as Edu } from './Edu/Edu'
export { default as Unity } from './Unity/Unity'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Contacts } from './Contacts/Contacts'
